[package]
name = "convexhull"
version = "0.1.0"
authors = ["Frederik Jacobsen <Frederik1904@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
clap = "2.33.3"
